name       : foomatic-filters
version    : 4.0.17
release    : 2
source     :
    - http://www.openprinting.org/download/foomatic/foomatic-filters-4.0.17.tar.gz : a2e2e53e502571e88eeb9010c45a0d54671f15707ee104f5c9c22b59ea7a33e3
license    : GPL-2.0
summary    : Universal print filter "foomatic-rip"
description: |
    The universal print filter "foomatic-rip", used by spoolers to convert PostScript job data into the printer's native format as described by a printer/driver-specific PPD file.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libcupsfilters)
rundeps    :
    - foomatic-db-engine
    - foomatic-db
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2015-8327.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
